### ISSUE TITLE
create POS Spanish-English mapping

### ISSUE THREAD

**Issue by KelseyJ22** [KelseyJ22/machine_translation#5]
Need to figure out what all the POS tags are and create a mapping of the following form:

spanish_pos:english_pos

so we can read it into a python dict and use it for lookup (I already wrote the code for reading/processing and uniq'd the Spanish and English POS tags, but I couldn't find what they all mean)

**Comment by kathawala** [comment]
I don't understand what needs to be done. Each Spanish POS tag does not correspond to an English POS tag. it's not a one-to-one mapping.

What do you want to do with the POS tags? I can implement that, but it isn't very possible to store a dict of Spanish POS tags hashed to English POS tags because several different Spanish POS tags can hash to one English POS tag, and some don't hash to any, etc.

I am going to work on using the English POS tags to make the translations make more sense in the meantime.

**Comment by kathawala** [comment]
Okay, so I'll go ahead and finish the "choose_best" method and implement adjective-noun switching on the English side if that is okay with you guys.

**Comment by kathawala** [comment]
I made the dict, it's not perfect, but it works. Since we only have a few tags, it ended up okay. I have also finished the "choose_best" method. Will implement adjective-noun switching later.

**Comment by KelseyJ22** [comment]
Hey sorry I just saw this now -- looks like you figured it out. I think it
should be fine that it's a many-to-one mapping; there's no reason different
keys can't have the same value, right?
